### ISSUE TITLE
100% CPU load

### ISSUE THREAD

**Issue by andrepue** [NyboTV/TP_ETS2_Plugin#10]
ETS_Dashoboard.exe uses all teh CPU time that is left from other programms, creating a permanent 100% CPU load. This affects everything on my Windows system, even when the Truck Simulator is not running (ATS or ETS2).
The used Funbit.Ets.Telemetry.Server already uses 6 up to 15% of my CPU time. Both together have a severe impact on The Windows System as well as thon the Truck Simulators (ATS and ETS). I am not using the newest Hardware, but with ETS_Dashboard and the Telemetry Server disabled I have a quite good gaming experience.

PC-Specs:
CPU: Intel Core I7 860 @2.80GHz
RAM: 16GB RAM
GPU: nVidia Geforce GTX1060 6GB
SSD: Crucial MX500 2TB + 1TB (SATA)
OS: Windows 10 Pro, Version 22H2, Build 19045.2486

ETS2 and ATS steam Version, several Mods.

Task-Manager before starting ETS_Dashboard.exe:
![Task_Manager_normal_load](https://user-images.githubusercontent.com/66639122/212565168-12b34730-ed5b-4b49-b586-9fa6da2e0233.png)

Task-Manager after starting ETS_Dashboard.exe, Truck Simulator not yet started:
![Task_Manager_high_load_after starting ETS_Dashboard](https://user-images.githubusercontent.com/66639122/212565175-57fa44c5-e349-47c9-b11f-dd1bbed1c242.png)

Other Programm Running are:
Google Chrome
Firefox
Discord
and of course: Touch Portal

**Comment by NyboTV** [comment]
Sorry for the late reply:
If you still have this problem, you can try this:

I have added a web page where you can disable unneeded "modules". As an example: TruckersMP. This will result in lower "refresh rates" and this will result in lower CPU usage. 

This plugin is not suitable for low-spec PCs. I am working on optimizing it, but my time is quite small. You can also try changing the refresh interval to something larger. Just go to the plugin folder -> Config and open "cfg.json" and change the "refreshinterval" number to something larger. This number is in ms. So 1000 would be 1 second.

Hope it helps until I have an optimized version.

**Comment by andrepue** [comment]
Thanks for the answer. I will try this out and let you know if this helps. At the time when I bought that PC it was almost the best you could get. Well, now an Core I3 is faster... time passes ;-)
