### ISSUE TITLE
Some states not working

### ISSUE THREAD

**Issue by Braste** [NyboTV/TP_ETS2_Plugin#18]
Some states are not working:

The engine state does not change, though the api returns the correct changed state, when the button is pressed:
   engineOn: false -> engineOn: true
   electricOn: false -> electricOn: true
Same for the parking brake:
   parkBrakeOn: true-> parkBrakeOn: false

Other states are working so I don't assume that the plugin can't communicate with the server.

To be specific, only the "If ... is" does not work:

![image](https://github.com/NyboTV/TP_ETS2_Plugin/assets/494984/adf32e1d-9266-4683-812b-cd13467cbb62)

This is working:

![image](https://github.com/NyboTV/TP_ETS2_Plugin/assets/494984/b146c470-5467-4208-97d3-2934042da185)

I am using the current version of ETS2, the current version of the plugin and the standard german page layout.

**Comment by NyboTV** [comment]
Can you try to create a new Page and create a test button to see if the state in general does nothing or only on the German edition?

**Comment by Braste** [comment]
It is indeed working on a new page. Did a simple test:
![image](https://github.com/NyboTV/TP_ETS2_Plugin/assets/494984/5caa91a7-69ce-4ada-819b-938e03a1e246)
